'use strict'

module.exports = {
  QUEUED_DELAYED_VALUE_CMD: 'QUEUED_DELAYED_VALUE_CMD',
  QUEUED_DELAYED_REJECT_CMD: 'QUEUED_DELAYED_REJECT_CMD',
  QUEUED_REJECT_CMD: 'QUEUED_REJECT_CMD',
  QUEUED_THROW_CMD: 'QUEUED_THROW_CMD',
  IMMEDIATE_VALUE_CMD: 'IMMEDIATE_VALUE_CMD',
  IMMEDIATE_THROW_CMD: 'IMMEDIATE_THROW_CMD',
  IMMEDIATE_REJECT_CMD: 'IMMEDIATE_REJECT_CMD'
}
