// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Repromise = require("@aantron/repromise/src/js/repromise.js");
var Registrar$ReduxSerialEffects = require("./Registrar.bs.js");

var IdleListeners = Registrar$ReduxSerialEffects.Make(/* module */[]);

function create(initialValue) {
  var queuePromise = /* record */[/* contents */Repromise.resolved(initialValue)];
  var match = Curry._1(IdleListeners[/* create */1], /* () */0);
  var getIdleListeners = match[1];
  var addToQueue = function (cb) {
    var currentPromise = /* record */[/* contents */Repromise.resolved(initialValue)];
    queuePromise[0] = Curry._1(cb, queuePromise[0]);
    Repromise.wait((function (param) {
            if (currentPromise[0] === queuePromise[0]) {
              return List.iter((function (cb) {
                            return cb();
                          }), Curry._1(getIdleListeners, /* () */0));
            } else {
              return 0;
            }
          }), queuePromise[0]);
    currentPromise[0] = queuePromise[0];
    return /* () */0;
  };
  return /* tuple */[
          addToQueue,
          match[0]
        ];
}

exports.IdleListeners = IdleListeners;
exports.create = create;
/* IdleListeners Not a pure module */
