// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Belt_MapInt = require("bs-platform/lib/js/belt_MapInt.js");

function Make(RegistrarListener) {
  var create = function (param) {
    var listeners = /* record */[/* contents */Belt_MapInt.empty];
    var nextListenerId = /* record */[/* contents */0];
    var register = function (fn) {
      nextListenerId[0] = nextListenerId[0] + 1 | 0;
      var currentId = nextListenerId[0];
      listeners[0] = Belt_MapInt.set(listeners[0], currentId, fn);
      return (function (param) {
          listeners[0] = Belt_MapInt.remove(listeners[0], currentId);
          return /* () */0;
        });
    };
    var getListeners = function (param) {
      return List.map((function (prim) {
                    return prim[1];
                  }), Belt_MapInt.toList(listeners[0]));
    };
    return /* tuple */[
            register,
            getListeners
          ];
  };
  return /* module */[
          /* ListenersMap */0,
          /* create */create
        ];
}

exports.Make = Make;
/* No side effect */
