// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Repromise = require("@aantron/repromise/src/js/repromise.js");

function dispatch(t, action) {
  return Repromise.Rejectable[/* catch */7]((function (error) {
                return Repromise.resolved(/* Error */Block.__(1, [error]));
              }), Repromise.Rejectable[/* map */5]((function (param) {
                    return /* Ok */Block.__(0, [/* () */0]);
                  }), t.dispatch(action)));
}

exports.dispatch = dispatch;
/* Repromise Not a pure module */
