// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Js_exn = require("bs-platform/lib/js/js_exn.js");
var Js_types = require("bs-platform/lib/js/js_types.js");

function fromJs(jsSubscriberResult) {
  var match = Js_types.classify(jsSubscriberResult);
  if (typeof match === "number") {
    switch (match) {
      case 2 : 
      case 3 : 
          return undefined;
      default:
        return Js_exn.raiseTypeError("Subscriber result must be undefined, object or array");
    }
  } else if (match.tag === 3) {
    var obj = match[0];
    var match$1 = Array.isArray(obj);
    if (match$1) {
      return obj;
    } else {
      return /* array */[obj];
    }
  } else {
    return Js_exn.raiseTypeError("Subscriber result must be undefined, object or array");
  }
}

exports.fromJs = fromJs;
/* No side effect */
